# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(350, 415)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.wordsLine = QtWidgets.QLineEdit(self.centralwidget)
        self.wordsLine.setGeometry(QtCore.QRect(10, 40, 311, 20))
        self.wordsLine.setObjectName("wordsLine")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 20, 191, 16))
        self.label.setObjectName("label")
        self.dirLine = QtWidgets.QLineEdit(self.centralwidget)
        self.dirLine.setGeometry(QtCore.QRect(10, 90, 231, 20))
        self.dirLine.setObjectName("dirLine")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 191, 16))
        self.label_2.setObjectName("label_2")
        self.setDirBtn = QtWidgets.QPushButton(self.centralwidget)
        self.setDirBtn.setGeometry(QtCore.QRect(250, 90, 71, 23))
        self.setDirBtn.setObjectName("setDirBtn")
        self.searchBtn = QtWidgets.QPushButton(self.centralwidget)
        self.searchBtn.setGeometry(QtCore.QRect(10, 130, 311, 23))
        self.searchBtn.setObjectName("searchBtn")
        self.filesWidget = QtWidgets.QListWidget(self.centralwidget)
        self.filesWidget.setGeometry(QtCore.QRect(10, 160, 311, 192))
        self.filesWidget.setObjectName("filesWidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 350, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Слова (фраза) для поиска"))
        self.label_2.setText(_translate("MainWindow", "Директория"))
        self.setDirBtn.setText(_translate("MainWindow", "..."))
        self.searchBtn.setText(_translate("MainWindow", "Поиск"))
